name: CI

on: [push]

jobs:
  build-humanitec:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Build and Push to Humanitec
        uses: humanitec/build-push-to-humanitec@v1
        with:
          humanitec-token: ${{ secrets.HUMANITEC_TOKEN }}
          organization: ${{ vars.HUMANITEC_ORG }}
  run-score:
    runs-on: ubuntu-latest
    needs: build-humanitec

    steps:
      - uses: actions/checkout@v3
      - uses: dorny/paths-filter@v2
        name: Check if score files have been updated
        id: changes
        with:
          filters: |
            scorefiles:
              - '**/score.yaml'
              - '**/humanitec.score.yaml'
      
      - name: Install score-humanitec
        if: steps.changes.outputs.scorefiles == 'true'
        run: |
          wget https://github.com/score-spec/score-humanitec/releases/download/0.5.0/score-humanitec_0.5.0_linux_amd64.tar.gz
          tar -xvf score-humanitec_0.5.0_linux_amd64.tar.gz
          chmod +x score-humanitec
          mv score-humanitec /usr/local/bin

      - name: Run Score
        if: steps.changes.outputs.scorefiles == 'true'
        run: |
          sed -i -E "s/^(\\s+image:)\\s+.*\$/\\1 'registry.humanitec.io\\/${{ vars.HUMANITEC_ORG }}\\/${GITHUB_REPOSITORY##*/}:${GITHUB_SHA}'/" score.yaml
          score-humanitec delta --retry --deploy --token ${{ secrets.HUMANITEC_TOKEN }} --org ${{ vars.HUMANITEC_ORG }} --app jotd --env development
